version: '3.1'

volumes:
  postgres_volume:

services:
  pg-local:
    image: postgres
    env_file:
      - .env
    ports:
      - "5555:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin  
      POSTGRES_DB: dbhw